# NUMPY


## Работа с библиотекой

### вызов библиотеки:

In [9]:
import numpy as np

### Установка библиотеки:

    conda install numpy
или
    pip install numpy

Синтаксис:

In [10]:
a = np.int64(25)
print(type(a))
print(np.iinfo(np.int64))
np.iinfo(a)
b = np.uint8(124)
np.finfo(np.float16)

<class 'numpy.int64'>
Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

Если операция проводится с двумя NumPy-типами с фиксированным объёмом памяти, в результате сохраняется наиболее «старший» тип:

In [11]:
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
# 1025
print(type(c))
# <class 'numpy.int32'>

1025
<class 'numpy.int32'>


## Типы данных:

In [12]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.complex128'>
<class 'numpy.complex256'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float128'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.longlong'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.ulonglong'>
<class 'numpy.void'>


In [13]:
print(np.uint8(-456))

56


## Массивы и векторы

### Создание массива

#### Создать массив из списка можно с помощью функции:

In [ ]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
arr.dtype

dtype('int64')

In [ ]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr


array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

#### Массив из нулей создаётся функцией np.zeros. 
Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж)

In [ ]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


#### Создание при поьощи range

Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: arange([start,] stop, [step,], dtype=None).


In [ ]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

#### Создание при помощи linspace (от, до, кол-во)

In [ ]:
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Узнаём шаг

In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45


#### Задать тип данных сразу при создании массива можно с помощью параметра dtype:

In [16]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

### ДЕЙСТВИЯ С МАССИВАМИ

#### Форма или структура массива хранится в атрибуте .shape:



In [ ]:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

#### Узнать размерность массива можно с помощью .ndim:

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)


nd_arr.ndim


2

#### Узнать общее число элементов в массиве можно с помощью .size  arr.size

#### узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize

#### поменять форму массива:

In [24]:
import numpy as np
arr = np.arange(8)

arr.shape = (2, 4)
arr


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
#или
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:
arr.reshape((2, 4), order='F')

#### транспонирование: arr_trans = arr.transpose()

#### ИНДЕКСЫ и СРЕЗЫ (всё как в списках)


print(arr[2])
print(arr[2:4])
print(arr[::-1])

в многомерных: nd_array[1, 2]
               nd_array[:2, 2]
               nd_array[:, 2:4]

#### СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

In [26]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)
#or

arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]
None
[ 3  4 12 12 15 23 23 45]


#### заполнить пропущенные значения 

например, нулями. Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»: roots[np.isnan(roots)] = 0 (вместо np.nan, в массив будут вставлены 0)

#### Примеры работы с массивами





import numpy as np

 Получите булевый массив с информацией о np.nan в массиве mystery
 True - значение пропущено, False - значение не пропущено
nans_index = np.isnan(mystery)

 В переменную n_nan сохраните число пропущенных значений
n_nan = sum(nans_index)

 Заполните пропущенные значения в массиве mystery нулями
mystery[nans_index] = 0

 Поменяйте тип данных в массиве mystery на int32
mystery = np.int32(mystery)

 Отсортируйте значения в массиве по возрастанию и сохраните
 результат в переменную array
array = np.sort(mystery)

 Сохраните в массив table двухмерный массив, полученный из массива array
 В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
 по столбцам! Например, 1, 2, 3, 4 -> 1    3
                                      2    4
table = array.reshape((5,3), order='F')

  Сохраните в переменную col столбец 2
col = table[:, 1]

ry:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery

 В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]

 В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]

 В переменную line_4 сохраните строку 4
line_4 = mystery[3]

 В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]

 Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
 Результат сохраните в переменную part
part = mystery[1:4, 2:5]

  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, -1]

 Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()

### РАБОТА С ВЕКТОРАМИ

In [27]:
#Длина вектора: Длиной вектора называют корень из суммы квадратов всех его координат
import numpy as np
vec=np.array([1,2,3])
length = np.sqrt(np.sum(vec ** 2)) 
#или функция norm
length = np.linalg.norm(vec)

Расстоянием между двумя векторами называют квадратный корень из суммы квадратов разностей соответствующих координат. 
Т.е. нвшли по парно разницу координат, возвели каждую пару в кв., сложили и нашли корень всего этого
(По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.)


In [28]:

vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
#или при помощи функции np.linalg.norm:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance


12.206555615733702

скалярным произведением двух векторов называют сумму произведений их соответствующих координат, Для этого используют функцию np.dot(x, y)

scalar_product = np.dot(vec1, vec2)

Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде: 
np.min(<vector>), 
так и в виде <vector>.min()

Функция mean позволяет посчитать среднее значение
vec.mean()

На сайте https://pyprog.pro/statistics_functions/statistics_function.html представлены доступные в NumPy статистические функции.

Статистика по массивам:
https://pyprog.pro/statistics_functions/statistics_function.html